language: go
go:
    - 1.1
    - 1.2
    - tip
install:
    - go get -v ./...
    - curl -L http://cpanmin.us | perl - -L=`pwd`/local App::cpanminus
    - export PATH=./local/bin:$PATH
    - ./local/bin/cpanm GrowthForecast
after_success:
    - go get github.com/mattn/goveralls
    - go get github.com/axw/gocov/gocov
    - go get code.google.com/p/go.tools/cmd/cover
    - export PATH="$HOME/gopath/bin:$PATH"
    - goveralls $COVERALLS_TOKEN
env:
    global:
        - secure: "PUMHk3jGfx/7WPrg9bI59iFoQG6IBd5tMhKwPjn7YutrgvsTI3MjFn2g+Wf7hCvp3wQgXCJEP2aOPLBe/RGK9Sp81qDwBAKGU7iR0p2MKvstgqKkh+CBybkG7YFeywPK4Ys/2kTnwBQmOJSIVOhodVyYhUzJ6yPUWbgaTv6f84k="
